### ISSUE TITLE
Invalid Template link on the bottom of the "Table - filter" page

### ISSUE THREAD

**Issue by jmoppel** [spapas/django-unpoly-demo#1]
First, great work on this demo! This is really terrific.

I found a small issue while viewing the `Table - filter` page. The Template link titled `core/company_table_filter.html core/company_list.html` at the bottom of the page points to the following invalid link:
https://github.com/spapas/django-unpoly-demo/tree/master/core/templates/core/company_table_filter.html%20core/company_list.html

The correct link ought to point to:
https://github.com/spapas/django-unpoly-demo/tree/master/core/templates/core/company_table_filter.html

**Comment by spapas** [comment]
Thank you! Fixed with [8beb1b4](https://github.com/spapas/django-unpoly-demo/commit/8beb1b45c16354e77b22cc9d27280a06095dac6b)
