### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by naveencom** [spapas/django-unpoly-demo#2]
Hi,

Can you please implement this demo in django function based views?

**Comment by spapas** [comment]
Hello @naveencom unfortunately I don't use function based views that much, see my rationale here: https://www.spapas.net/2022/09/28/django-guidelines/#use-class-based-views 

I think that if you understand CBVs a bit it shouild not be difficult to convert the CBVs to functional views.

**Comment by naveencom** [comment]
Please see my rationale on using function based views. 

https://spookylukey.github.io/django-views-the-right-way/
